name: Node.js Docker CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Build Docker Image
      - name: Build Docker Image
        run: docker build -t todo-app-frontend:latest .

      # 2. Lưu Image thành file
      - name: Save Docker Image
        run: docker save todo-app-frontend:latest > todo-app.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: todo-app.tar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      # 3. CHỈ copy file Image lên Server (Không cần copy config nữa vì đã có Git lo)
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "todo-app.tar"
          target: "~/project/Todo-App"

      # 4. Kéo Code từ Git -> Load Image -> Deploy
      - name: Docker Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/project/FB-Todo-App/Todo-App
            
            # --- BƯỚC MỚI: KÉO CODE TỪ GIT ---
            # Reset cứng để đồng bộ 100% với nhánh main trên Github, xóa bỏ mọi thay đổi rác trên VM
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
            # Load image từ file tar
            docker load < todo-app.tar
            
            # Khởi chạy bằng Compose (Lúc này nó sẽ dùng các file config mới nhất vừa kéo về)
            docker compose up -d
            
            # Dọn dẹp các image cũ để tiết kiệm ổ cứng
            docker image prune -f
